language: node_js
node_js:
- '14'
script:
- echo 'Starting...'
- echo 'Going into back-end & installing dependencies...'
- cd back-end
- npm install
- echo 'Testing back-end...'
- npm test
- echo 'Going into front-end & installing dependencies...'
- cd ../front-end
- npm install
- echo 'Testing front-end...'
- npm test
env:
  global:
    secure: YFrx+PBPWPq1df+dmRfssL2ygWdLEf3ovYpcaW1VzRgco09ZJm9jdXuKn+otIKToLLNRU/npn2vi9RqymLAt96RA3nyyrHmYdgq+cX8c9epzcMvtePfcHjB2Ok6iWIKIVyMpZw99/qrKwQlFFKw7XyzFEnW90ZEk5i/oXXFaYeeVflM1OutU4LJa6xlOsdY+s8dW/Fcd76aR5K7HvT9to2J3Jd1uLkAvH0THye1arqljvBu3AGQ92z5CvYc+9nmzMWwFRt6cWvoCQILOX2pJ3exTkLz2Xvke64gp4gAUtc3Ekz3VgnZPZlNLzBeOO7Q+V/h2Ae34YqjBFLKbjZDsSB7O3NNYVp8xdQ+zDQDbywqyrr4CUdwbCtdHtUuGuXzlmtfV6gOTAiYgJQVZsNDL0tc8AYUPWgT82U2FxE7bvNIVh/6eBCsM6JEVKBiDh/dqMbSJg3y1Y2Pup6bMcBTB5lSTXLUpNE9nD/h+6Tn1CN6jdKfmuMa7cTEWlSiOb9L56c5DO1j01860IZKXJAqsZNUPO8U2MAxcAixXmnVmAC1pFyLkQNSEAzg7/1YVhl+WGxq/KENaXiDBjWK7Kgyx58C3JH15lZyo5tpf3R59mkgQk5NMAKtqP9iSJHkJhou0S16+B5GdRcTRr325NtkeUGHaSy4NY0XpzsuUGGnHly4=
branches:
  only:
  - master
